const NA='暂无数据';let DATA=null;let activeFilter='all';const $=id=>document.getElementById(id);const ok=v=>Number.isFinite(v);const fmt=(v,s='')=>ok(v)?`${v}${s}`:NA;
function choose(){const funds=DATA.funds||[];const known=funds.filter(f=>ok(f.premium));const scored=funds.filter(f=>ok(f.score)).sort((a,b)=>b.score-a.score);const low=[...known].sort((a,b)=>a.premium-b.premium)[0];return{best:scored[0]||low,low,known};}
function renderHeader(){const{known}=choose();$('updatedAt').textContent=DATA.updated_at||NA;$('sourceNote').textContent=DATA.source_note||NA;$('underFiveCount').textContent=known.filter(f=>f.premium<=5).length+'只';$('underThreeCount').textContent=known.filter(f=>f.premium<=3).length+'只';$('todayMove').textContent=fmt(DATA.risk?.change1,'%');}
function renderDecision(){const{best,low}=choose();$('bestCode').textContent=best?.code||NA;$('bestName').textContent=best?`${best.company}${best.name||'纳指100 ETF'}`:NA;$('bestGrade').textContent=best?.grade||(!best?NA:'按已知溢价临时推荐');$('bestPremium').textContent=fmt(best?.premium,'%');$('bestFee').textContent=fmt(best?.fee,'%');$('bestTracking').textContent=best?.tracking||NA;$('bestReason').textContent=best?.reason||(!best?NA:'当前缺少完整评分数据，暂按已知溢价较低排序。');$('lowestCode').textContent=low?.code||NA;$('lowestName').textContent=low?`${low.company}${low.name||'纳指100 ETF'}`:NA;$('lowestPremium').textContent=fmt(low?.premium,'%');$('toThree').textContent=low?`${Math.max(0,low.premium-3).toFixed(2)}%`:NA;$('toFive').textContent=low?`${Math.max(0,low.premium-5).toFixed(2)}%`:NA;$('baseZone').textContent=!low?NA:low.premium<=3?'已在3%以内，为底仓区':low.premium<=5?'已在5%以内，为观察区':'尚未进入5%观察区';$('buySignal').textContent=!low?NA:low.premium<=3?'建议投入 10%～20%':low.premium<=5?'建议投入 5%～10%':low.premium<=10?'建议小仓观察':'建议继续等待';$('buyChecks').innerHTML=[`当前最低溢价：${fmt(low?.premium,'%')}`,`VIX恐慌指数：${fmt(DATA.risk?.vix)}`,`纳指100指数：${fmt(DATA.risk?.ndx)}`,`近20日涨跌：${fmt(DATA.risk?.change20,'%')}`,`20日波动率：${fmt(DATA.risk?.vol20,'%')}`].map(x=>`<li>✅ ${x}</li>`).join('');}
function renderTop(){let list=[...(DATA.funds||[])];const scored=list.filter(f=>ok(f.score));list=(scored.length?scored.sort((a,b)=>b.score-a.score):list.filter(f=>ok(f.premium)).sort((a,b)=>a.premium-b.premium)).slice(0,3);$('topFunds').innerHTML=list.length?list.map((f,i)=>`<article class="mini"><span class="rank">${i+1}</span><strong>${f.code}</strong><p>${f.company}${f.name||'纳指100 ETF'}</p><div class="metrics three"><div><span>费率</span><b>${fmt(f.fee,'%')}</b></div><div><span>跟踪误差</span><b>${f.tracking||NA}</b></div><div><span>溢价</span><b>${fmt(f.premium,'%')}</b></div></div></article>`).join(''):`<p>${NA}</p>`;}
function renderRisk(){const r=DATA.risk||{};const rows=[['VIX恐慌指数',fmt(r.vix)],['纳指100指数',fmt(r.ndx)],['近20日涨跌幅',fmt(r.change20,'%')],['20日年化波动率',fmt(r.vol20,'%')],['60日年化波动率',fmt(r.vol60,'%')],['PE（TTM）',fmt(r.pe)]];$('riskGrid').innerHTML=rows.map(([k,v])=>`<div class="risk-row"><span>${k}</span><b>${v}</b></div>`).join('');$('trendVix').textContent=fmt(r.vix);$('trendNdx').textContent=fmt(r.ndx);$('trendVol').textContent=fmt(r.vol20,'%');}
function pass(f){if(activeFilter==='under3')return ok(f.premium)&&f.premium<=3;if(activeFilter==='under5')return ok(f.premium)&&f.premium<=5;if(activeFilter==='wait')return ok(f.premium)&&f.premium>5;if(activeFilter==='weak')return f.tracking==='偏弱';return true;}
function renderFunds(){const sort=$('sortSelect').value;let list=(DATA.funds||[]).filter(pass);list.sort((a,b)=>sort==='premium'?((a.premium??999)-(b.premium??999)):((b.score??-1)-(a.score??-1)));$('fundList').innerHTML=list.map(f=>`<article class="fund-item"><div class="fund-head"><div><strong>${f.code} ${f.company}</strong><div>${f.name||'纳指100 ETF'}</div></div><div class="premium">${fmt(f.premium,'%')}</div></div><div class="details"><div>综合评分<b>${fmt(f.score)}</b></div><div>综合费率<b>${fmt(f.fee,'%')}</b></div><div>跟踪情况<b>${f.tracking||NA}</b></div><div>推荐等级<b>${f.grade||NA}</b></div></div></article>`).join('')||`<article class="fund-item">${NA}</article>`;}
function tabs(){document.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-target]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.target||((b.dataset.target==='long-term'||b.dataset.target==='risk')&&p.id==='decision')));if(b.dataset.target==='long-term')$('long-term').scrollIntoView({behavior:'smooth'});if(b.dataset.target==='risk')$('risk').scrollIntoView({behavior:'smooth'});}));}
async function start(){try{const res=await fetch(`data.json?t=${Date.now()}`);if(!res.ok)throw Error();DATA=await res.json();renderHeader();renderDecision();renderTop();renderRisk();renderFunds();}catch(e){document.body.insertAdjacentHTML('afterbegin','<div class="card">数据加载失败，请稍后刷新。</div>');}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;activeFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderFunds();});$('sortSelect').addEventListener('change',()=>DATA&&renderFunds());$('refreshBtn').addEventListener('click',()=>location.reload());tabs();start();